---
- name: Read files playbook
  hosts: localhost
  tasks:
  - name: read variable files
    lineinfile:
      path: "{{ item | regex_replace('([^.]*).*', '/tmp/\\1.ip') }}"
      create: yes
      line: "{{ lookup('file', item) | regex_search('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') | default('No Ipadress', true) }}"
    loop: "{{ files }}"
